apiVersion: v1
data:
  DATABABSE_URL: bW9uZ29kYitzcnY6Ly9yb290LXVzZXI6bXd0WjA5QWR2SjIyWXZiRkBhdXRoLW1pY3Jvc2VydmljZS1kYi5wZmZoa3dwLm1vbmdvZGIubmV0L0F1dGhEQg==
  JWT_SECRET: RXN0b0RlYmVEZVMzclVuU3RyaW5nU2VndXJvMTIzOSoqKg==
kind: Secret
metadata:
  creationTimestamp: "2024-07-31T01:20:55Z"
  name: auth-secrets
  namespace: default
  resourceVersion: "12660"
  uid: 43d73a51-1fd8-4ae3-81ae-c80c762d3e93
type: Opaque
